# Generated by Django 5.0.4 on 2026-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
