# Generated by Django 5.0.4 on 2026-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0002_organisation_is_staff_organisation_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
