# Generated by Django 5.0.4 on 2026-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0003_remove_organisation_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='extra_kpi',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
