# Generated by Django 5.0.4 on 2026-03-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0004_callanalysis_extra_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
