# Generated by Django 5.0.4 on 2026-03-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0006_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('lead_score', models.IntegerField(default=0)),
                ('temperature', models.CharField(default='Cold', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aos_agent.organisation')),
            ],
        ),
    ]
