# Generated by Django 5.0.4 on 2026-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0010_team_org_controls_call_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Org Admin'), ('team_lead', 'Team Lead'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
