# Generated by Django 5.0.4 on 2026-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0012_organisation_number_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='number_quota',
            field=models.PositiveIntegerField(default=4, help_text='Max unique phone numbers this org can call.'),
        ),
    ]
