# Generated by Django 5.0.4 on 2026-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0014_allowedphonenumber_orgrequest_manualanalysis_call'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allowedphonenumber',
            name='unique_org_phone',
        ),
        migrations.AlterField(
            model_name='orgrequest',
            name='industry',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('healthcare', 'Healthcare'), ('cosmetics', 'Cosmetics / Retail'), ('apartment', 'Apartment / Property Management'), ('generic', 'Generic')], default='generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='orgrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='allowedphonenumber',
            unique_together={('org', 'phone')},
        ),
        migrations.AlterModelTable(
            name='manualanalysis',
            table='manual_analysis',
        ),
    ]
