# Generated by Django 5.0.4 on 2026-04-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0017_organisation_numbers_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualanalysis',
            name='call',
        ),
        migrations.RemoveField(
            model_name='manualanalysis',
            name='routing_type',
        ),
        migrations.AlterModelTable(
            name='manualanalysis',
            table='aos_agent_manualanalysis',
        ),
    ]
