# Generated by Django 5.0.4 on 2026-04-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0018_remove_manualanalysis_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualanalysis',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_analyses', to='aos_agent.calllog'),
        ),
        migrations.AddField(
            model_name='manualanalysis',
            name='routing_type',
            field=models.CharField(blank=True, choices=[('sales_only', 'Sales Only'), ('service_only', 'Service Only'), ('service_then_sales', 'Service → Sales Transfer')], default='sales_only', max_length=20),
        ),
        migrations.AlterModelTable(
            name='manualanalysis',
            table='manual_analysis',
        ),
    ]
