# Generated by Django 5.0.4 on 2026-04-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0019_manualanalysis_call_manualanalysis_routing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualanalysis',
            name='call',
        ),
        migrations.RemoveField(
            model_name='manualanalysis',
            name='routing_type',
        ),
        migrations.AlterModelTable(
            name='manualanalysis',
            table='aos_agent_manualanalysis',
        ),
    ]
