# Generated by Django 5.0.4 on 2026-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos_agent', '0023_calllog_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='call_limit_seconds',
            field=models.IntegerField(default=120, help_text='Maximum call duration in seconds (0 = no limit). Call is gracefully stopped after this duration.'),
        ),
    ]
